### ISSUE TITLE
BUG: signal() error on dashboard.

### ISSUE THREAD

**Issue by SteffenJahr** [BoundfoxStudios/kuwaka-wakati#36]
<img width="841" alt="Screenshot 2023-06-25 at 21 49 05" src="https://github.com/BoundfoxStudios/kuwaka-wakati/assets/7164777/6d94a106-2db9-4095-9565-0f31f3791ff5">

Happens when I start the app

**Comment by ManuelRauber** [comment]
fixed in https://github.com/BoundfoxStudios/kuwaka-wakati/commit/914b0119d9094326641d524eb5c51119be1be435
